[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_demo3 = "BQmo3cEsGEzNHXCPKUqvtTkEH3Epz4Prq9LQQMVQHV8z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/surenmovsisyan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
